#!/bin/bash
#
# 50_gen_ssl_keys.sh
#

KEY_DIR="/config/keys"
CRT="${KEY_DIR}/cert.crt"
KEY="${KEY_DIR}/cert.key"
CNF="${KEY_DIR}/openssl-selfsigned.cnf"

# Self-signed policy (generic).
DAYS_VALID=825
RENEW_WITHIN_DAYS=30

# Marker so we only auto-rotate our own autogenerated certs.
AUTOGEN_O="Self-Signed"
AUTOGEN_OU="AUTOGEN"
AUTOGEN_CN="localhost"

rc=0
need_gen=0
reason=""

is_our_cert()
{
	local subj=""

	subj="$(openssl x509 -in "${CRT}" -noout -subject 2>/dev/null)"
	if echo "${subj}" | grep -q "O=${AUTOGEN_O}" && echo "${subj}" | grep -q "OU=${AUTOGEN_OU}"; then
		return 0
	fi

	return 1
}

cert_expires_within_days()
{
	local days="$1"
	local seconds=0

	seconds=$((days * 86400))

	# Returns 0 if cert is valid for at least "seconds" from now; non-zero otherwise.
	openssl x509 -in "${CRT}" -noout -checkend "${seconds}" >/dev/null 2>&1
	return $?
}

ensure_selfsigned_cnf()
{
	if [[ -s "${CNF}" ]]; then
		return 0
	fi

	cat > "${CNF}" <<EOF
[req]
distinguished_name = dn
x509_extensions = v3_req
prompt = no

[dn]
C = US
ST = NA
L = NA
O = ${AUTOGEN_O}
OU = ${AUTOGEN_OU}
CN = ${AUTOGEN_CN}

[v3_req]
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
IP.1 = 127.0.0.1
EOF

	return 0
}

generate_cert()
{
	ensure_selfsigned_cnf

	# Generate certificate.
	openssl req -x509 -nodes -days "${DAYS_VALID}" -newkey rsa:2048 \
		-out "${CRT}" \
		-keyout "${KEY}" \
		-config "${CNF}" \
		>/dev/null 2>&1

	# Basic sanity checks.
	openssl x509 -in "${CRT}" -noout >/dev/null 2>&1
	if [[ $? -ne 0 ]]; then
		return 1
	fi

	openssl rsa -in "${KEY}" -noout -check >/dev/null 2>&1
	if [[ $? -ne 0 ]]; then
		return 1
	fi

	return 0
}

# Ensure key directory exists.
mkdir -p "${KEY_DIR}" >/dev/null 2>&1

# Decide if we need to generate/renew. Use -s to reject zero-byte files.
if [[ -s "${KEY}" && -s "${CRT}" ]]; then
	is_our_cert
	if [[ $? -eq 0 ]]; then
		# Our autogenerated cert ? rotate if expired or near expiry.
		cert_expires_within_days "${RENEW_WITHIN_DAYS}"
		if [[ $? -ne 0 ]]; then
			need_gen=1
			reason="(autogen cert expiring/expired)"
		fi
	else
		# User-provided cert ? do not modify, but warn if expired.
		cert_expires_within_days 0
		if [[ $? -ne 0 ]]; then
			echo "WARNING: TLS certificate in ${KEY_DIR} is expired. Please replace it."
		fi
	fi
else
	need_gen=1
	reason="(missing/empty cert/key)"
fi

if [[ ${need_gen} -eq 1 ]]; then
	echo "Generating self-signed keys in ${KEY_DIR} ${reason}, you can replace these with your own keys if required"

	# Remove any partial outputs first.
	rm -f "${CRT}" "${KEY}" >/dev/null 2>&1

	generate_cert
	if [[ $? -ne 0 ]]; then
		echo "ERROR: Failed to generate self-signed certificate in ${KEY_DIR}"
		rc=1
	else
		echo "Self-signed certificate generated (valid ${DAYS_VALID} days, SAN=localhost/127.0.0.1)"
	fi
else
	echo "Using existing keys in \"${KEY_DIR}\""
fi

chown abc:abc "${CRT}" >/dev/null 2>&1
chmod 600 "${CRT}" >/dev/null 2>&1

chown abc:abc "${KEY}" >/dev/null 2>&1
chmod 600 "${KEY}" >/dev/null 2>&1

exit ${rc}
